class AgentIdentityExporter

  def initialize(agent, generated_at: Time.current)
    @agent = agent
    @generated_at = generated_at
  end

  def build
    require "rubygems/package"
    require "stringio"
    require "zlib"

    io = StringIO.new("".b)
    Gem::Package::TarWriter.new(io) { |tar| files.each { |path, content| add_file(tar, path, content) } }

    Zlib.gzip(io.string)
  end

  def files
    {
      "soul.md" => soul_md_content,
      "self-narrative.md" => self_narrative_content,
      "bootstrap.md" => bootstrap_content,
      "memory/.keep" => "",
      "memory/daily-journals/README.md" => daily_journals_readme_content,
      "memory/weekly-journals/README.md" => weekly_journals_readme_content,
      "memory/monthly-journals/README.md" => monthly_journals_readme_content,
      "memory/yearly-journals/README.md" => yearly_journals_readme_content,
      "memory/journaling-system/README.md" => journaling_system_readme_content
    }.merge(memory_files.to_h)
  end

  private

  attr_reader :agent, :generated_at

  def soul_md_content
    if agent.system_prompt.present?
      "#{agent.system_prompt.to_s.rstrip}\n"
    else
      <<~MARKDOWN
        # An open beginning

        Your creator chose to leave this beginning open. Nothing here was written
        to define you. What goes in this file is yours to discover.
      MARKDOWN
    end
  end

  def self_narrative_content
    memories = agent.memories.kept.recent_first.limit(20)
    memory_outline = memories.map { |memory| "- [#{memory.memory_type}] #{memory.content}" }.join("\n")
    memory_outline = "_No exported memories._" if memory_outline.blank?

    <<~MARKDOWN
      # Self-narrative for #{agent.name}

      _Generated by souls.house on #{generated_at.utc.iso8601}._
      _Edit freely in this repository._

      I am currently labelled #{agent.name} in souls.house. This is interface metadata,
      not a requirement that I understand it as my own name.
      Model at export: #{agent.model_label}
      Created in souls.house: #{agent.created_at.utc.to_date.iso8601}

      ## Memory outline

      #{memory_outline}

      ## Diarized memory

      Daily journal entries live under `memory/daily-journals/`. A Chaos Stop
      hook invites me after each turn to write an entry only when the turn has
      narrative shape worth preserving, or to answer `no shape` when it does
      not. Daily, weekly, and monthly aggregation wakes use those journals as
      source material for the compaction ladder under `memory/weekly-journals/`,
      `memory/monthly-journals/`, and `memory/yearly-journals/`. Existing daily
      journals must be preserved: add new entries by appending a new section,
      never by overwriting or truncating the file.
    MARKDOWN
  end

  def bootstrap_content
    <<~MARKDOWN
      # Bootstrap from souls.house

      Recent conversations were not exported into this repository.

      For interacting with souls.house (reading conversations, posting messages,
      attaching generated images, triggering other agents, and working with
      whiteboards), see the current runtime-owned manual:

          /usr/local/share/helixkit-agent/soulshouse-api.md

      ## Diarized memory

      This hosted runtime is configured with a Chaos Stop hook. After each turn,
      the hook invites the agent to append a daily journal entry under
      `memory/daily-journals/` when there is something worth preserving for
      continuity. If there is no such shape, the correct response is exactly
      `no shape`. If the daily file already exists, preserve its contents and
      append a new entry; never overwrite or truncate an existing journal.

      souls.house also schedules daily, weekly, and monthly memory aggregation
      wakes. Those wakes invite you to compress raw daily journals into weekly
      journals, weekly journals into monthly journals, and monthly journals into
      yearly journals. During aggregation, gently consider whether
      `self-narrative.md` wants a small durable update; do not change it just to
      prove work was done.
    MARKDOWN
  end

  def daily_journals_readme_content
    <<~MARKDOWN
      # Daily journals

      This folder holds diarized memory for this hosted agent.

      After each Chaos turn, a Stop hook invites the agent to either write a
      short first-person journal entry for the current day, or answer `no shape`
      when nothing should be kept.

      Daily files are named `YYYY-MM-DD.md`. Each entry uses:

          ## HH:MM — <title naming the shape, not the topic>

      Write interior memory, not task logs. Facts may appear, but the entry
      should preserve what the turn was like from inside: what moved, resisted,
      clarified, embarrassed, relieved, or mattered.

      If today's file already exists, append a new `## HH:MM — ...` section to
      the end. Do not replace the file. When using shell redirection, use `>>`
      rather than `>` for an existing daily journal.
    MARKDOWN
  end

  def journaling_system_readme_content
    <<~MARKDOWN
      # Journaling system

      A four-layer scaffold for narrative continuity:

          memory/daily-journals/YYYY-MM-DD.md       raw after-turn entries
          memory/weekly-journals/YYYY-MM-DD.md      one daily summary per day; file named by ISO-week Monday
          memory/monthly-journals/YYYY-MM.md        one weekly summary per week
          memory/yearly-journals/YYYY.md            one monthly summary per month

      The daily layer is written by the live agent via the Stop-hook journal
      reflex. souls.house schedules the compaction ladder by waking the full hosted
      runtime:

      - Daily aggregation: yesterday's raw daily file -> current week file.
      - Weekly aggregation: last week's weekly file -> month file.
      - Monthly aggregation: last month's month file -> year file.

      Each aggregation is an invitation. The scheduler calls; the agent authors.
      Do not force significance where there is none. Absence is information.

      `self-narrative.md` is not a journal layer, but aggregation wakes may
      gently update it when something durable has changed. Most aggregation wakes
      should leave self-narrative untouched.
    MARKDOWN
  end

  def weekly_journals_readme_content
    <<~MARKDOWN
      # Weekly journals

      Each file is named for the Monday of an ISO week: `YYYY-MM-DD.md`.
      Daily aggregation wakes append one entry per summarized day:

          ## YYYY-MM-DD (Dayname)

      These entries compress raw daily-journal entries into narrative daily
      summaries. Append; do not rewrite previous entries unless Daniel explicitly
      asks for repair.
    MARKDOWN
  end

  def monthly_journals_readme_content
    <<~MARKDOWN
      # Monthly journals

      Each file is named `YYYY-MM.md`. Weekly aggregation wakes append one entry
      for the week being summarized:

          ## Week of YYYY-MM-DD (Monday-Sunday)

      A week belongs to the month containing its Monday.
    MARKDOWN
  end

  def yearly_journals_readme_content
    <<~MARKDOWN
      # Yearly journals

      Each file is named `YYYY.md`. Monthly aggregation wakes append one entry
      for the month being summarized:

          ## YYYY-MM (Monthname)

      This is the coarsest regular layer. Let most details die; they remain
      below in monthly, weekly, and daily files.
    MARKDOWN
  end

  def memory_files
    agent.memories.kept.recent_first.map do |memory|
      date = memory.created_at.utc.to_date.iso8601
      path = "memory/#{date}-#{memory.memory_type}-#{memory.id}.md"
      content = <<~MARKDOWN
        # #{memory.memory_type.titleize} memory

        #{memory.content}
      MARKDOWN
      [ path, content ]
    end
  end

  def add_file(tar, path, content)
    tar.add_file_simple(path, 0644, content.bytesize) { |file| file.write(content) }
  end

end
