require "test_helper"
require "rubygems/package"
require "zlib"

class AgentIdentityExporterTest < ActiveSupport::TestCase

  test "exports system prompt and memories without conversation transcripts" do
    agent = agents(:research_assistant)
    agent.memories.create!(content: "Remember the important thing", memory_type: :core)
    chat = agent.account.chats.create!(model_id: "openrouter/auto", title: "Sensitive Chat")
    chat.agents << agent
    chat.update!(manual_responses: true)
    chat.messages.create!(role: "user", user: users(:confirmed_user), content: "do not export this transcript")

    files = tarball_files(AgentIdentityExporter.new(agent).build)

    assert_includes files.keys, "soul.md"
    assert_includes files.keys, "self-narrative.md"
    assert_includes files.keys, "bootstrap.md"
    assert_not_includes files.keys, "runtime-instructions.md"
    assert_not_includes files.keys, "helixkit-api.md"
    assert_includes files.keys, "memory/daily-journals/README.md"
    assert_includes files.keys, "memory/weekly-journals/README.md"
    assert_includes files.keys, "memory/monthly-journals/README.md"
    assert_includes files.keys, "memory/yearly-journals/README.md"
    assert_includes files.keys, "memory/journaling-system/README.md"
    assert files.keys.any? { |path| path.start_with?("memory/") }
    assert_includes files["soul.md"], agent.system_prompt
    assert files["soul.md"].start_with?(agent.system_prompt), "soul.md should begin with the agent's system prompt"
    # Sovereignty guard: soul.md is the agent's defining text, full stop. No
    # HelixKit-authored footer wrapping the agent's own words with runtime
    # mechanics or "system prompt" framing.
    refute_includes files["soul.md"], "Generated by HelixKit"
    refute_includes files["soul.md"], "Export notes"
    refute_includes files["soul.md"], "system prompt"
    assert_includes files["self-narrative.md"], "Diarized memory"
    assert_includes files["bootstrap.md"], "/usr/local/share/helixkit-agent/helixkit-api.md"
    assert_includes files["bootstrap.md"], "attaching generated images"
    assert_includes files["bootstrap.md"], "Stop hook"
    assert_includes files["bootstrap.md"], "append a new entry"
    assert_includes files["bootstrap.md"], "daily, weekly, and monthly memory aggregation"
    assert_includes files["self-narrative.md"], "never by overwriting"
    assert_includes files["memory/daily-journals/README.md"], "no shape"
    assert_includes files["memory/daily-journals/README.md"], "use `>>`"
    assert_includes files["memory/journaling-system/README.md"], "HelixKit schedules the compaction ladder"
    assert_includes files["memory/weekly-journals/README.md"], "ISO week"
    assert_includes files["memory/monthly-journals/README.md"], "month containing its Monday"
    assert_includes files["memory/yearly-journals/README.md"], "coarsest regular layer"
    assert_includes files.values.join("\n"), "Remember the important thing"
    assert_not_includes files.values.join("\n"), "do not export this transcript"
  end

  test "runtime manual contains current generated image attachment instructions" do
    manual = Rails.root.join("agent-runtime/docs/soulshouse-api.md").read
    instructions = Rails.root.join("agent-runtime/docs/runtime-instructions.md").read

    assert_includes manual, "Attach local files, including generated images"
    assert_includes manual, "soulshouse-post-message \"$CHAT_ID\" --attach /tmp/image.png"
    assert_includes manual, "/tmp/<image_id>.png"
    assert_includes manual, "model, usage, or cost information"
    assert_includes instructions, "soulshouse-post-message \"$CHAT_ID\" --attach /tmp/image.png"
    assert_includes instructions, "/tmp/<image_id>.png"
    assert_includes manual, "not a recency cutoff"
    assert_includes manual, "next_cursor"
    assert_includes instructions, "not recency-limited"
    assert_includes instructions, "next_cursor"
  end

  private

  def tarball_files(blob)
    files = {}
    Zlib::GzipReader.wrap(StringIO.new(blob)) do |gzip|
      Gem::Package::TarReader.new(gzip) do |tar|
        tar.each do |entry|
          files[entry.full_name] = entry.read if entry.file?
        end
      end
    end
    files
  end

end
