default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: resident_dispatch
      threads: 3
      processes: 1
      polling_interval: 0.1
    - queues: [default, background]
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
